[phases.setup]
nixPkgs = ['nodejs_18']

[phases.install]
cmds = ['npm install --only=production --no-audit --no-fund']

[phases.build]
cmds = ['npm install --include=dev', 'npm run build']

[start]
cmd = 'npm start'

[variables]
NODE_ENV = 'production'